I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/sh_date.rpy", line 88, in script
    with none
  File "game/scripts/sh_date.rpy", line 88, in <module>
    with none
NameError: name 'none' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/sh_date.rpy", line 88, in script
    with none
  File "renpy/ast.py", line 1436, in execute
    trans = renpy.python.py_eval(self.expr)
  File "renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/scripts/sh_date.rpy", line 88, in <module>
    with none
NameError: name 'none' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Zucchiniverse v4.1.22
Sun Apr  3 19:54:02 2022
