I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 79, in script
    pov "Wait, don't touch m-"
Exception: Sayer 'pov' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 79, in script
    pov "Wait, don't touch m-"
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'pov' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Zucchiniverse 1.0
Sun Mar 27 11:17:42 2022
